//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 三相智慧能源网关调试软件.UserLoginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserLoginServiceReference.IUserLogin")]
    public interface IUserLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserLogin/Login", ReplyAction="http://tempuri.org/IUserLogin/LoginResponse")]
        bool Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserLogin/Login", ReplyAction="http://tempuri.org/IUserLogin/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserLoginChannel : 三相智慧能源网关调试软件.UserLoginServiceReference.IUserLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserLoginClient : System.ServiceModel.ClientBase<三相智慧能源网关调试软件.UserLoginServiceReference.IUserLogin>, 三相智慧能源网关调试软件.UserLoginServiceReference.IUserLogin {
        
        public UserLoginClient() {
        }
        
        public UserLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
    }
}
